### ISSUE TITLE
How to get timestamp from Ds1302::DateTime objects ?

### ISSUE THREAD

**Issue by gusantor** [Treboada/Ds1302#10]
Hello

I'm using Ds1302 library on an attiny85. It works ok.

I need to do some calculations with dates. I look for "timstamp" but no luck.

Is it possible to get a timestamp for a given date or from the RTC ?

I also installed TimeLib library to get timestamps, but it does misbehave when Ds1302 is running aside

Please can you give some advice on getting timestamps from Ds1302::DateTime objects ?

Thanks

**Comment by rafacouto** [comment]
Hi @gusantor ,

Ds1302::DateTime struct was created to be mapped with the DS1302 internal time fields:

```c
        typedef struct {
            uint8_t year;
            uint8_t month;
            uint8_t day;
            uint8_t hour;
            uint8_t minute;
            uint8_t second;
            uint8_t dow;
        } DateTime;
```

This library should keep simple and **it won't implement specific conversions to another computer types**. Anyway, it's possible to implement a function by yourself using some well-known algorithms / functions like [explained in this post](https://blog.reverberate.org/2020/05/12/optimizing-date-algorithms.html).

Moreover, as you've mentioned the [GeekFactory TimeLib Library](https://github.com/geekfactory/TimeLib), here is an example that sets a *timelib_tm* variable from a Ds1302::DateTime and uses `timelib_make()` function from _TimeLib_:

```c
      // get the current time from DS1302 RTC
      Ds1302 rtc(PIN_ENA, PIN_CLK, PIN_DAT);
      Ds1302::DateTime now;
      rtc.getDateTime(&now);

      // set the current time in the timelib
      timelib_tm tinfo;
      tinfo.tm_year = now.year;
      tinfo.tm_mon = now.month;
      tinfo.tm_mday = now.day;
      tinfo.tm_hour = now.hour;
      tinfo.tm_min = now.minute;
      tinfo.tm_sec = now.second;
      timelib_set(timelib_make(&tinfo));
```

**Comment by gusantor** [comment]
Thank you @rafacouto.

I have managed to use TimeLib to translate Ds1302::DaTeTime to unix timestamp with

```c++
Ds1302::DateTime now;
rtc.getDateTime(&now);
time_t t = gDate(now);

time_t gDate(Ds1302::DateTime now){
  tE = {now.second, now.minute, now.hour, now.dow, now.day, now.month, now.year+30};
  time_t now3  = makeTime(tE);
  return now3;  
}
```

Thanks
