### ISSUE TITLE
undefined reference to `shiftOut'

### ISSUE THREAD

**Issue by nikowot** [Treboada/Ds1302#5]
Hello,
I got this error, compiling a a previously correct program incl. Your library DS1302 v 1.0.4 in Arduino IDE 2.0.3:

_**C:\Users\Me\AppData\Local\Temp\ccOl8sUg.ltrans0.ltrans.o: In function `_writeByte':
C:\Users\Me\Documents\Arduino\libraries\DS1302/DS1302.cpp:382: undefined reference to `shiftOut'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1**_

Platform: Arduino UNO

Please check if it can be corrected?

Greetings,

**Comment by rafacouto** [comment]
@nikowot No 'shiftOut' symbol in this library... Are you sure you have not modified this source code? [shiftOut  seems a function from the Arduino library](https://www.arduino.cc/reference/en/language/functions/advanced-io/shiftout/)...

**Comment by nikowot** [comment]
Hello,
My program was not modified and it is as follows:

#include <Wire.h>
#include <LiquidCrystal_I2C.h>
// Set the LCD address to 0x3F for a 16 chars and 2 line display // note: it may be different for your LCD please find it.
LiquidCrystal_I2C lcd(0x27, 16, 2);
#include <DS1302.h>
// Init the DS1302
DS1302 rtc(11, 12, 13);
// Init a Time-data structure
Time t;

void setup()
{
// Set the clock to run-mode, and disable the write protection
 //rtc.halt(false);
 //rtc.writeProtect(false);

 // The following lines can be commented out to use the values already stored in the DS1302
 //rtc.setDOW(SUNDAY); // Set Day-of-Week to TUESDAY
 //rtc.setTime(8, 37, 00); // Set the time to 24hr format it will automatically take time according to AM/PM
 //rtc.setDate(03, 5, 2020); // Set the date to Febrauray 6th, 2018
 // initialize the LCD
 lcd.begin();
}

void loop()
{
 lcd.clear();
 
 // Get data from the DS1302
 t = rtc.getTime();
 lcd.setCursor(0, 0);
 if (t.date<=9){
 lcd.setCursor(0,0);
 lcd.print("0");
 lcd.setCursor(1,0);
 lcd.print(t.date, DEC);
 }
 else {
 lcd.print(t.date, DEC);}
 
 lcd.setCursor(3, 0);
 lcd.print(rtc.getMonthStr());
 lcd.print(" ");
 //lcd.setCursor(12,0);
 lcd.print(t.year,DEC);
 lcd.setCursor(4,1);

 lcd.setCursor(4,1);
 lcd.print("0");
 lcd.setCursor(5,1);
 lcd.print(t.hour, DEC);

 
 lcd.setCursor(6,1);
 lcd.print(":");
 lcd.setCursor(7,1);
 if (t.min<=9){
 lcd.setCursor(7,1);
 lcd.print("0");
 lcd.setCursor(8,1);
 lcd.print(t.min, DEC);
 }
 else {
 lcd.print(t.min, DEC);}

 lcd.setCursor(9,1);
 lcd.print(":");
 lcd.setCursor(10,1);
 if (t.sec<=9){
 lcd.setCursor(10,1);
 lcd.print("0");
 lcd.setCursor(11,1);
 lcd.print(t.sec, DEC);
 }
 else {
 lcd.print(t.sec, DEC);}
 delay (1000);
 
}

**Comment by rafacouto** [comment]
Man, you are not using Treboada/Ds1302 library. You are using another one: notice the name of the method names at the[ Ds1302 class](https://github.com/Treboada/Ds1302/blob/master/src/Ds1302.h).

**Comment by nikowot** [comment]
Thank you for the solution.
